global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 1h
  receiver: discord

receivers:
  - name: discord
    discord_configs:
      - webhook_url: 'https://discord.com/api/webhooks/1490046446853030040/Szccmb7OVf2vaDwX3S7Lu59eMIWipBI3OQIAgEKOyvG0mV8zEwjAgrn1jAeCbeX6TIT6'
        title: '{{ .Status | toUpper }}: {{ .CommonLabels.alertname }}'
        message: |
          {{ range .Alerts }}
          **Alert:** {{ .Annotations.summary }}
          **Severity:** {{ .Labels.severity }}
          **Instance:** {{ .Labels.instance }}
          {{ end }}
