global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 1h
  receiver: discord

receivers:
  - name: discord
    slack_configs:
      - api_url: 'https://discord.com/api/webhooks/1490046446853030040/Szccmb7OVf2vaDwX3S7Lu59eMIWipBI3OQIAgEKOyvG0mV8zEwjAgrn1jAeCbeX6TIT6/slack'
        channel: '#alerts'
        send_resolved: true
        title: '{{ .Status | toUpper }}: {{ .CommonLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Severity:* {{ .Labels.severity }}
          {{ end }}
